### ISSUE TITLE
CP_root sometimes fails, and some other times it does not

### ISSUE THREAD

**Issue by marcoCalipari** [GarryFCR/Rsa_Zkp#1]
Hi!

First of all, thanks for the implementation! It looks nice.
Secondly, I was trying to integrate this module into my go code, and while doing some tests, I realized that the root verification sometimes fails and sometimes does not.
I tried to review the paper again to double-check the operations, and everything seemed okay. 
So I was wondering, si this behaviour normal? If so, what is the cause of the nondeterministic result? Thanks!

**Comment by marcoCalipari** [comment]
Update: I noticed the disclaimer in the readme. However it does not specify which values should be in the bound. If you could elaborate more I am eager to place some checks in order to avoid the possible failing

**Comment by GarryFCR** [comment]
Hi, I implemented this a long time ago and might need some fixes and security checks . I don't have the bandwidth to review/recap  and make fixes at the moment, I do however suggest you take a look at the sub protocols and verify if they have been implemented correctly.

**Comment by marcoCalipari** [comment]
I understand,

The only piece of information that I am missing right now is regarding this part of the readme:

> Root verification may fail when values are not within the bound defined by Lamdas

It would be nice to know which values or lamdas I should take care of. It would significantly help to avoid going around the whole root implementation.
I will take care of making the fixes, no issue; I just do not understand where and what
Best

**Comment by GarryFCR** [comment]
Any ephemeral values that are processed by these sub protocols.

**Comment by marcoCalipari** [comment]
I was able to fix it,  refer to PR #2
